version: "3"
services:
  directus:
    name: Directus
    image: directus/directus:10.4
    volumes:
      - uploads:/directus/uploads
    environment:
      - KEY="${DIRECTUS_KEY}"
      - SECRET="${DIRECTUS_SECRET}"
      - DB_CLIENT=pg
      - DB_CONNECTION_STRING="${DB_CONNECTION_STRING}"
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - CACHE_REDIS="${CACHE_REDIS}"
      - ADMIN_EMAIL="${ADMIN_EMAIL}"
      - ADMIN_PASSWORD="${ADMIN_PASSWORD}"
      - CACHE_AUTO_PURGE=true
      - PUBLIC_URL="${PUBLIC_URL}"
    ports:
      - 8055:8055