version: '3'
services:
  directus:
    container_name: Directus
    image: directus/directus:10.4
    volumes:
      - ./uploads:/directus/uploads
    environment:
      DB_CLIENT: pg
      CACHE_ENABLED: true
      CACHE_STORE: redis
      CACHE_AUTO_PURGE: true
